name: build

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'README_zh-CN.md'
      - 'docs/**'
      - 'examples/**'
      - '.dev_scripts/**'
    branches:
      - main

  pull_request:
    paths-ignore:
      - 'README.md'
      - 'README_zh-CN.md'
      - 'docs/**'
      - 'examples/**'
      - '.dev_scripts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_cpu:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
        torch: [1.6.0, 1.7.0, 1.8.0, 1.9.0]
        include:
          - torch: 1.6.0
            torchvision: 0.7.0
          - torch: 1.7.0
            torchvision: 0.8.1
          - torch: 1.8.0
            torchvision: 0.9.0
          - torch: 1.9.0
            torchvision: 0.10.0
          - torch: 1.8.0
            torchvision: 0.9.0
            python-version: 3.9
          - torch: 1.9.0
            torchvision: 0.10.0
            python-version: 3.8
          - torch: 1.9.0
            torchvision: 0.10.0
            python-version: 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install pip --upgrade
      - name: Install Pillow
        run: pip install Pillow==6.2.2
        if: ${{matrix.torchvision == '0.4.1'}}
      - name: Install PyTorch
        run: pip install torch==${{matrix.torch}}+cpu torchvision==${{matrix.torchvision}}+cpu -f https://download.pytorch.org/whl/torch_stable.html
      - name: Install MMCV
        run: pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cpu/torch${{matrix.torch}}/index.html
      - name: Install MMDet
        run: pip install mmdet
      - name: Install other dependencies
        run: pip install -r requirements.txt
      - name: Build and install
        run: rm -rf .eggs && pip install -e .
      - name: Run unittests and generate coverage report
        run: |
          coverage run --branch --source mmocr -m pytest tests/
          coverage xml
          coverage report -m

  build_cu101:
    runs-on: ubuntu-18.04
    container:
      image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel
      env:
        LANG: C.UTF-8
    strategy:
      matrix:
        python-version: [3.7]
        torch: [1.6.0+cu101, 1.7.0+cu101, 1.8.0+cu101]
        include:
          - torch: 1.6.0+cu101
            torch_version: 1.6.0
            torchvision: 0.7.0+cu101
          - torch: 1.7.0+cu101
            torch_version: 1.7.0
            torchvision: 0.8.1+cu101
          - torch: 1.8.0+cu101
            torch_version: 1.8.0
            torchvision: 0.9.0+cu101
          - torch: 1.8.0+cu101
            torch_version: 1.8.0
            torchvision: 0.9.0+cu101
            python-version: 3.6
          - torch: 1.8.0+cu101
            torch_version: 1.8.0
            torchvision: 0.9.0+cu101
            python-version: 3.8
          - torch: 1.8.0+cu101
            torch_version: 1.8.0
            torchvision: 0.9.0+cu101
            python-version: 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Add ppa source repo for python3.9.
      - name: Add python3.9 source
        run: |
          apt-get update && apt-get install -y software-properties-common
          add-apt-repository -y ppa:deadsnakes/ppa
        if: ${{matrix.python-version == '3.9'}}
      # Install python-dev for some packages which require libpython3.Xm.
      # Github's setup-python cannot install python3.9-dev, so we have to use apt install.
      # Set DEBIAN_FRONTEND=noninteractive to avoid some interactions.
      - name: Upgrade pip
        run: python -m pip install pip --upgrade
      - name: Install Python-dev
        run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python${{matrix.python-version}}-dev
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6
          apt-get clean
          apt-get install -y curl
      - name: Install Pillow
        run: python -m pip install Pillow==6.2.2
        if: ${{matrix.torchvision < 0.5}}
      - name: Install librosa and soundfile
        run: python -m pip install librosa soundfile
      - name: Install lmdb
        run: python -m pip install lmdb
      - name: Install PyTorch
        run: python -m pip install torch==${{matrix.torch}} torchvision==${{matrix.torchvision}} -f https://download.pytorch.org/whl/torch_stable.html
      - name: Install mmocr dependencies
        run: |
          python -m pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch${{matrix.torch_version}}/index.html
          python -m pip install mmdet
          python -m pip install -r requirements.txt
      - name: Build and install
        run: |
          rm -rf .eggs
          python setup.py check -m -s
          TORCH_CUDA_ARCH_LIST=7.0 python -m pip install -e .
      - name: Run unittests and generate coverage report
        run: |
          coverage run --branch --source mmocr -m pytest tests/
          coverage xml
          coverage report -m
      # Only upload coverage report for python3.7 && pytorch1.5
      - name: Upload coverage to Codecov
        if: ${{matrix.torch == '1.6.0+cu101' && matrix.python-version == '3.7'}}
        uses: codecov/codecov-action@v1.0.14
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false

  build_cu102:
    runs-on: ubuntu-18.04
    container:
      image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel
    strategy:
      matrix:
        python-version: [3.7]
        torch: [1.9.0+cu102]
        include:
          - torch: 1.9.0+cu102
            torch_version: 1.9.0
            torchvision: 0.10.0+cu102
          - torch: 1.9.0+cu102
            torch_version: 1.9.0
            torchvision: 0.10.0+cu102
            python-version: 3.8
          - torch: 1.9.0+cu102
            torch_version: 1.9.0
            torchvision: 0.10.0+cu102
            python-version: 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install pip --upgrade
      - name: Install Python-dev
        run: apt-get update && apt-get install -y python${{matrix.python-version}}-dev
        if: ${{matrix.python-version != 3.9}}
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6
          apt-get clean
          rm -rf /var/lib/apt/lists/*
          apt-get install -y ninja-build
      - name: Install Pillow
        run: python -m pip install Pillow==6.2.2
        if: ${{matrix.torchvision < 0.5}}
      # - name: Install TurboJpeg lib
      #   run: apt-get install -y libturbojpeg
      - name: Install soundfile lib
        run: apt-get install -y libsndfile1
      - name: Install librosa and soundfile
        run: python -m pip install librosa soundfile
      - name: Install lmdb
        run: python -m pip install lmdb
      - name: Install PyTorch
        run: python -m pip install torch==${{matrix.torch}} torchvision==${{matrix.torchvision}} -f https://download.pytorch.org/whl/torch_stable.html
      - name: Install mmocr dependencies
        run: |
          python -m pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch${{matrix.torch_version}}/index.html
          python -m pip install mmdet
          python -m pip install -r requirements.txt
      - name: Build and install
        run: |
          rm -rf .eggs
          python setup.py check -m -s
          TORCH_CUDA_ARCH_LIST=7.0 python -m pip install -e .
      - name: Run unittests and generate coverage report
        run: |
          coverage run --branch --source mmocr -m pytest tests/
          coverage xml
          coverage report -m
